apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URL
              value: "mongodb://ramraj:ram07@mongo-service:27017/airbnb-db"  # MongoDB URI for connection
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets  # The secret name
                  key: mongodbUser      # MongoDB user key
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets  # The secret name
                  key: mongodbPassword  # MongoDB password key
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets  # The secret name
                  key: mongodbRootPassword  # MongoDB root password key
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets  # The secret name
                  key: secretkey  # Application secret key for JWT or other secure uses
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
