apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: {{ .Values.mongodb.service.type }}
  selector:
    app: mongo  # Should match the label in the MongoDB deployment
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
