apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-secrets
  namespace: default
type: Opaque
data:
  mongodbRootPassword: cm9vdHVzZXI=      # Base64 encoded root password (ramraj)
  mongodbUser: cmFtcmFq                     # Base64 encoded user (ramraj)
  mongodbPassword: cmFtMDc=                 # Base64 encoded password (ram07)
  secretkey: amFybWFyNDEy                   # Base64 encoded secret key (ramar412)

