apiVersion: v1
kind: Service
metadata:
  name: mongo-service  # Ensure this matches the mongoUri reference
spec:
  type: {{ .Values.mongodb.service.type }}
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
