apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  secret-key: {{.Values.secrets.secretkey}}
  mongodb-root-password: {{ .Values.secrets.mongodbRootPassword | b64enc }}
  mongodb-username: {{ .Values.secrets.mongodbUser | b64enc }}
  mongodb-password: {{ .Values.secrets.mongodbPassword | b64enc }}