frontend:
  image: "ramraj214/airbnb-frontend-v1.slim"  # Frontend image
  replicas: 2
  containerPort: 80  # Now set to port 80 for production serve
  service:
    type: LoadBalancer
    port: 80           # Expose on the standard HTTP port
    targetPort: 80     # Map to the container's port 80
  livenessProbe:
    httpGet:
      path: /           # Root path, adjust if needed
      port: 80          # Update the liveness probe to match the exposed port
    initialDelaySeconds: 10
    periodSeconds: 10

backend:
  image: "ramraj214/airbnb-backend:latest"
  replicas: 2
  containerPort: 4000
  service:
    type: ClusterIP
    port: 4000
    targetPort: 4000
  livenessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 10
    periodSeconds: 10

mongodb:
  image: "mongo:latest"
  replicas: 1
  containerPort: 27017
  mongoDbName: "airbnb-db"
  mongoUri: "mongodb://mongo:27017/airbnb-db"
  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017
  volumeMounts:
    - name: mongodb-data
      mountPath: /data/db

secrets:
  mongodbRootPassword: "cm9vdHVzZXI="   # Base64 encoded password
  mongodbUser: "cmFtcmFq"                # Base64 encoded user
  mongodbPassword: "QFJhbTA3"            # Base64 encoded password
  secretkey: "amFybWFyNDEy"              # Base64 encoded secret key
