frontend:
  image: "ramraj214/airbnb-frontend:latest"
  replicas: 2
  containerPort: 80
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 10

backend:
  image: "ramraj214/airbnb-backend:latest"
  replicas: 2
  containerPort: 4000
  backendUrl: "http://backend-service:4000"
  service:
    type: ClusterIP
    port: 4000
    targetPort: 4000
  livenessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 10
    periodSeconds: 10
  env:
    - name: MONGO_URI
      value: "mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@mongo-service:27017/airbnb-db"
    - name: MONGODB_USER
      valueFrom:
        secretKeyRef:
          name: mongodb-secret
          key: mongodbUser
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-secret
          key: mongodbPassword

mongodb:
  image: "mongo:latest"
  replicas: 1
  containerPort: 27017
  mongoDbName: "airbnb-db"
  mongoUri: "mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@mongo-service:27017/airbnb-db"
  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017
  volumeMounts:
    - name: mongodb-data
      mountPath: /data/db

secrets:
  mongodbRootPassword: cm9vdHVzZXI=      # Base64 encoded root password (ramraj)
  mongodbUser: cmFtcmFq                     # Base64 encoded user (ramraj)
  mongodbPassword: cmFtMDc=                 # Base64 encoded password (ram07)
  secretkey: amFybWFyNDEy
                            
          